apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions: # Sync options which modifies sync behavior
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.

  source:
    repoURL: https://github.com/mazelab/argocd-root-basics.git
    path: charts/metrics
    targetRevision: {{ .Values.branch }}
    helm:
      valuesObject:
